# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Yanmir G]
paypal: # Replace with a single Paypal @CarlosYanmir
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://paypal.me/CarlosYanmir?country.x=PE&locale.x=es_XC']
